<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Filter</name>
   <tag></tag>
   <elementGuidId>9149d4c9-da87-4c2d-bf39-2f94bf1f733c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Post'])[1]/following::h1[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.filter-heading</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>a0c2ea8c-025b-46ca-b84c-140c23e2681d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter-heading</value>
      <webElementGuid>4f8f02f1-379e-4a8a-ba76-c6aab24988e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Filter</value>
      <webElementGuid>c7117160-cba9-4261-a7aa-5a1baa29b169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-lms-container[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;learner-container&quot;]/div[1]/app-community[@class=&quot;ng-star-inserted&quot;]/div[1]/section[@class=&quot;content-section&quot;]/div[@class=&quot;content-section-sub-container&quot;]/div[1]/div[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator filter-background&quot;]/div[1]/h1[@class=&quot;filter-heading&quot;]</value>
      <webElementGuid>9184ca2b-206c-479f-9eec-9ab1843a9ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Post'])[1]/following::h1[1]</value>
      <webElementGuid>083f1689-cf8f-4eaa-9081-78a4fe944e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doubts'])[1]/preceding::h1[1]</value>
      <webElementGuid>956f45ca-9166-4bd0-a32a-350aca50ed0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[1]/preceding::h1[1]</value>
      <webElementGuid>9058f96d-12c3-4657-b937-29928b8b7dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Filter']/parent::*</value>
      <webElementGuid>1d37468e-9386-4447-ae83-df30fe9793e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card/div/h1</value>
      <webElementGuid>0fb48b1d-b24b-4b5e-8dd6-a0c11c91939d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Filter' or . = 'Filter')]</value>
      <webElementGuid>4d26eff8-3d7f-47e0-97b3-140c036300cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
