<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Jobs</name>
   <tag></tag>
   <elementGuidId>b4ab6482-9efe-4c6a-ae28-98aec416a307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello Learner(Post by facilitator)'])[1]/following::h1[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>mat-card.mat-card.mat-focus-indicator.content-card.jobs-card.ng-star-inserted > mat-card-title.mat-card-title > h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>22d22a53-1e35-4143-8730-44982a579c65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jobs</value>
      <webElementGuid>db3ac9b8-423c-48f7-abad-ce34f058f9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-lms-container[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;learner-container&quot;]/div[1]/app-home[@class=&quot;ng-star-inserted&quot;]/app-learner-home[@class=&quot;ng-star-inserted&quot;]/section[@class=&quot;content-section&quot;]/div[1]/div[1]/mat-card[@class=&quot;mat-card mat-focus-indicator content-card jobs-card ng-star-inserted&quot;]/mat-card-title[@class=&quot;mat-card-title&quot;]/h1[1]</value>
      <webElementGuid>3a6a9da3-f7df-4f63-9678-d484acd94e4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello Learner(Post by facilitator)'])[1]/following::h1[1]</value>
      <webElementGuid>0757ec0a-9b30-4890-b204-2a64bbe5e479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tibil Facilitator'])[1]/following::h1[1]</value>
      <webElementGuid>67d1491b-10ea-4ad7-9b06-88d24aa9669c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test Job,'])[1]/preceding::h1[1]</value>
      <webElementGuid>d54a7b72-f4cf-4c6b-9f71-a2bed48a9ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Focaloid'])[1]/preceding::h1[1]</value>
      <webElementGuid>4f941bed-ae8b-4151-9481-bb6306961936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jobs']/parent::*</value>
      <webElementGuid>f157c816-2d80-4e74-baa1-43456903a784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card[3]/mat-card-title/h1</value>
      <webElementGuid>21c4beb3-6b42-435d-90f0-0a8872f74d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Jobs' or . = 'Jobs')]</value>
      <webElementGuid>4e8a2102-97a6-4d76-b572-3484a7b54c21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
