<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_English_mat-select-arrow ng-tns-c89-1</name>
   <tag></tag>
   <elementGuidId>de29f376-7f8d-4442-9ea0-0496d6e4182f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-select[@id='mat-select-0']/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-select-arrow.ng-tns-c89-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>351dd423-e535-4be8-9ba0-af0bce8d71f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-arrow ng-tns-c89-1</value>
      <webElementGuid>79838b01-a51b-4bd4-bd14-9381aaa74ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-0&quot;)/div[@class=&quot;mat-select-trigger ng-tns-c89-1&quot;]/div[@class=&quot;mat-select-arrow-wrapper ng-tns-c89-1&quot;]/div[@class=&quot;mat-select-arrow ng-tns-c89-1&quot;]</value>
      <webElementGuid>37fcd150-f85f-485a-8293-f8416a3675d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-select[@id='mat-select-0']/div/div[2]/div</value>
      <webElementGuid>8a0835d6-8a22-48f9-9f7e-df9b9d1215ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>b2599551-b1f4-4bca-aca9-96ddb5afae2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
