<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EnglishLanguage</name>
   <tag></tag>
   <elementGuidId>27337612-385d-4713-869e-6ec7290e96a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c87-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ef84e72b-9214-4a0c-bf4b-b4aa87dfb9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c87-0</value>
      <webElementGuid>5cb647eb-d3b4-4745-a3b6-fd0a51edbe76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EnglishLanguage</value>
      <webElementGuid>5aeb8c0b-280f-40ca-87a8-cce3b0241bf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-login[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;core-container&quot;]/div[@class=&quot;language-select&quot;]/app-language-select[1]/mat-form-field[@class=&quot;mat-form-field language ng-tns-c87-0 mat-accent mat-form-field-type-mat-select mat-form-field-appearance-legacy mat-form-field-can-float mat-form-field-has-label ng-untouched ng-pristine ng-valid ng-star-inserted mat-form-field-should-float&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c87-0&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c87-0&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c87-0&quot;]</value>
      <webElementGuid>2e4b12fa-d9ef-42e4-bd0e-3a3006d1c3c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>7ab43f9b-fefc-447b-ae35-b28fe3990c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EnglishLanguage' or . = 'EnglishLanguage')]</value>
      <webElementGuid>8292c4b7-a723-4d9c-9e80-2653ce1053dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
